import Footer from "./components/Footer";
import ModalBody from "./components/ModalBody";
import Modal from "./components/ModalBody";
import Navbar from "./components/Navbar";
import "./globals.css";
import { GlobleStateContextProvider } from "./context/StateContext";

export const metadata = {
  title: "Blogify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" mx-[170px] bg-gray-50">
        <GlobleStateContextProvider>
          <>
            <Navbar />
            {children}
            <Footer />
          </>
        </GlobleStateContextProvider>
      </body>
    </html>
  );
}
